// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopClientServise.DtoModels;

public partial class Users
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public virtual ICollection<Comments> Comments { get; } = new List<Comments>();
}