// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopApiServise.Models;

public partial class Addresses
{
    public int AddressId { get; set; }

    public int? UserId { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string ZipCode { get; set; }

    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();

    public virtual Users User { get; set; }
}