// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PetShopApiServise.Models;

public partial class Comments
{
    public int CommentId { get; set; }

    [Required]
    public int? AnimalId { get; set; }

    [Required(ErrorMessage = "Please enter a comment")]
    [MinLength(5, ErrorMessage = "Comment must be at least 5 characters long")]
    [MaxLength(100, ErrorMessage = "The comment cant be larger than 100 chars")]
    public string Comment { get; set; }

    public int? UserId { get; set; }

    public virtual Animals Animal { get; set; }

    public virtual Users User { get; set; }
}