// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace PetShopApiServise.Models;

public partial class Comments
{
    public int CommentId { get; set; }

    [Required(ErrorMessage = "Please, you must inseret an animal")]
    public int? AnimalId { get; set; }

    [Required(ErrorMessage = "Please enter a comment")]
    [StringLength(100, MinimumLength = 10, ErrorMessage = "Comment must be between 10 and 100 characters")]
    public string Comment { get; set; }


    [Required]
    public string UserId { get; set; }

    public virtual Animals Animal { get; set; }
}