// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopApiServise.Models;

public partial class Comments
{
    public int CommentId { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public int? AnimalId { get; set; }

    public string CommentText { get; set; }

    public DateTime CommentDate { get; set; }

    public virtual Animals Animal { get; set; }

    public virtual PetProducts Product { get; set; }

    public virtual Users User { get; set; }
}