// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopApiServise.Models;

public partial class Discounts
{
    public int DiscountId { get; set; }

    public string Code { get; set; }

    public decimal DiscountPercentage { get; set; }

    public DateTime ExpirationDate { get; set; }

    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();
}