// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopApiServise.Models;

public partial class PetSales
{
    public int SaleId { get; set; }

    public int? UserId { get; set; }

    public int? AnimalId { get; set; }

    public DateTime SaleDate { get; set; }

    public decimal Price { get; set; }

    public virtual Animals Animal { get; set; }

    public virtual Users User { get; set; }
}