// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetShopApiServise.Models;

public partial class ShippingOptions
{
    public int ShippingOptionId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string EstimatedDeliveryTime { get; set; }

    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();
}