// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace PetShopApiServise.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string Username { get; set; }
}